### PR TITLE
Add fusion installation

### PR DESCRIPTION
**Pull request by Gil-1**
Add small description to install the plugin with Fusion

### CODE REVIEW

**Comment by jonahfriedman** [comment]
Thanks for this, will look at reviewing and getting it in soon.  I definitely agree installation instructions for Fusion are needed.

**Comment by cedricduriau** [comment]
Hi @Gil-1 

Will be there at next release!

Cheers
Cedric

**Comment by Gil-1** [comment]
Great news :)

Thanks !

**Comment by cedricduriau** [comment]
Hi all!

The README of 1.2.0.b6 now holds a 3 step explanation on how to install cryptomatte!

Cheers
Cedric

**Comment by Gil-1** [comment]
Thanks !

**Pull request closed without merging**
