### PR TITLE
fusion cryptomatte

### PR DESCRIPTION
**Pull request by cedricduriau**
Cryptomatte fuse along with two required modules (simplejson and struct, lmurmurhash is not in use).

### CODE REVIEW

**Comment by acjones** [comment]
Hey Cedric,

I'm finally getting around to testing this today.  Honestly, I don't think either Jonah or myself has much hesitation to merge the pull request, since it doesn't affect anything else, and it would be good to make this available for feedback from other Fusion users ASAP.

I did notice one thing from messing around with it in Fusion.  Right now when I look at the output of the Cryptomatte node, I'm not seeing anything in the alpha channel.  If I click on the "Matte Only" option, I do see a matte, as well as the same matte in the RGB channels.  Are you seeing that same behavior, or is it just me?  In our Nuke implementation, everything works the same for the preview keys, except you also get the matte in the alpha channel.  Most of our users just leave the node in the normal mode and use the alpha mattes directly, since it's one less click and it's easier to go back to the node and change the keys.

- Andy

**Comment by cedricduriau** [comment]
Hi Andy

Although I am still messing around with dynamic inputs, this could absolutely be a v1.0.0.

So that's why the preview has nothing in the alpha. I can rewrite some code to put the matte result inside the preview image instead of creating a new image only holding the matte. The matte result image the fuse creates now has 4 channels because Fusion handles mono channel images differently (object type Bitmap) than multi channel images (object type Image).

What I can do is, the same as Nuke, put the matte result inside the alpha channel of the preview image and when "Matte Only" is checked, display the matte result as a mono channel alpha image. This way the fuse can output a standard image with the matte result in the alpha, and a more efficient mono channel image if the user wants to work with Bitmap objects.

What are your thoughts on this?

Cheers
Cedric

**Comment by acjones** [comment]
Hey Cedric,

What I'd suggest is the following:

"Matte Only Unchecked"
RGBA image with the preview channels as you have them in RGB, plus the matte in the A channel.

"Matte Only Checked"
As you have it currently.  (I don't have any objection to using a mono image if there's a reason to do so, like better efficiency, but we don't do that currently in Nuke).


We had a couple of other thoughts.  None of this necessarily has to be fixed before we merge, so it's up to you if you want to try to fix any of it now, or on a subsequent commit.

Jonah noticed is that it doesn't currently work to key based on numerical inputs, instead of hash name.  For example, it should be possible to key the background by typing "<0.0>" in the Matte List text input, without quotes.  The method here is just parsing the string, and then directly keying the numerical value.  This isn't critically important, but can be useful in cases where the manifest is broken or incomplete for some reason.


Is it currently necessary to have all 4 inputs?  I noticed that if I left off uCryptoMaterial02, I get an error.  Is there any way to make it ignore the disconnected inputs if only the first 2 or 3 are connected?


We also were talking a bit about the setup issues for multiple inputs.  Do you know if it would work to use channel assignments like this:

Red: uCryptoMaterial.R
Green: uCryptoMaterial.G
Blue: uCryptoMaterial00.R
Alpha: uCryptoMaterial00.G
Z: uCryptoMaterial00.B
Coverage: uCryptoMaterial00.A
Object ID: uCryptoMaterial01.R
Material ID: uCryptoMaterial01.G
U: uCryptoMaterial01.B
V: uCryptoMaterial01.A
X Normal: uCryptoMaterial02.R
Y Normal: uCryptoMaterial02.G
Z Normal: uCryptoMaterial02.B
X Velocity: uCryptoMaterial02.A


I can imagine this sort of thing might be frowned upon, but it seems like the user experience might be far better dealing with a single input.  It might also be easier to script a loader to detect a Cryptomatte image, and set all the channels, rather than trying to auto-connect inputs to the Cryptomatte Fuse.  Dealing with a single input stream would also have advantages if you wanted do things like crop the image before keying.  

I'm not sure if there are any gotchas with bit depths on the other channels, but it's hard to imagine them ever being used with Cryptomatte the usual way.  For example, Cryptomatte images wouldn't ever have an Object ID, since they already are object IDs...  This would probably be a bigger change than some of the other things I just mentioned, but it also might break people's comps if this changed at a later date...  We could maybe work around it by checking for more than one input, but then it means the Fuse would need to work in both modes, which could add some complexity.

(BTW, you may notice I left out uCryptoMaterial.B.  This is because it's not really necessary for generating user previews, and having the one extra channel allows you to go all the way up to uCryptoMaterial04.A if you use every Fusion channel)

What do you think?

- Andy

**Comment by cedricduriau** [comment]
Hi Andy

First of all, I see you merged the code and I wanted to show some gratitude for always helping me out with extra info about cryptomatte and trusting my code enough to actually merge it as is.

Now it is normally not my type to commit & push without leaving a message, but one of the implementation you were referring to was actually quick to implement.

What I committed, as you've probably seen and tested, is the implementation of the mattes being in the alpha channel of the preview image, when matte only remains unchecked. When checked, the final matte image inside the alpha channel of the preview image gets copied into the alpha channel of a new mono channel image. I kept the mono channel image as you mentioned for performance reasons.

About the numerical inputs, what actually is the value you input to key mattes with? Is it the id float value? If this is so, when as you mention the manifest is broken and you still want to key a matte, how do you actually know the value of the id to input? I reckon the pro of this feature but does broken manifests happen often / when does a manifest actually break?

It is currently necessary to have all 4 inputs, now that you mention this, I remember that only the first 2 ranks are needed to create a keyable image. So it is indeed redundant to break when the others aren't connected. This is a feature I will definitely implement.

Before I start on multiple inputs, I must say I am still trying to implement dynamic inputs in a workable way. My goal is to make the fuse usable from only one UI handling, such as connecting one exr cryptomatte loader with the master input of the fuse, and from there on auto generate (code wise or Fusion tool wise) all inputs needed to work properly with channels set correctly. The assignment you wrote is indeed frowned upon due to it's very unstructured nature. My main concern is future proofing this idea. If I apply the logic you mentioned, we can go to 6 ranks max. Will the future bring up above 6-8 ranks or not? Because If I can pull of the dynamic inputs, the amount of ranks is out of the discussion. But don't get me wrong, it is still a valid option to explore. I actually had this working in an early stage but ran out of slots when populating ALL the RGBA channels from every rank when dealing with 6 ranks. 

What concerns depths of channel slots does not matter, it happens on the loader side If I am correct. I don't think you can assign different depths to different channels of the same loader in Fusion. But indeed populating other slots may be a problem in some specific comps using them for a good reason. There will always be a workaround I guess, but you may understand I want to explore the clean way out before going that route.

I will keep you all up the date on further dev / questions. Small detail on the README file on the homepage of the repo, my name is spelled wrong. I would appreciate it if this would change from Credric to Cedric, no egos were hurt in the process don't worry.

Again, thank you all, from both Kristof and I, for the trust and helpfulness, it still is a pleasure to work on this neat tool.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
Sorry about the type-o in your name, I went ahead and fixed that really quick. We'll get back to you about everything else very soon. Thanks!

**Comment by jonahfriedman** [comment]
> About the numerical inputs, what actually is the value you input to key mattes with? Is it the id float value? If this is so, when as you mention the manifest is broken and you still want to key a matte, how do you actually know the value of the id to input? 

If a keyed ID can't be found in the manifest, the value is added instead of the name. If that value isn't in the manifest, it gets added to the matte list instead in the format <0.0>. 

>  does broken manifests happen often / when does a manifest actually break?

There are a bunch of reasons that are usually renderer specific stuff. Such as the manifest is written when the render starts, and the geometry/names might not all be available at that time. Also we don't write manifests that are too large to the header. 

> My main concern is future proofing this idea. If I apply the logic you mentioned, we can go to 6 ranks max. Will the future bring up above 6-8 ranks or not? 

Possibly.. but I still don't know of any instance of anybody changing the default value of 6 in the real world, except when they were trying to troubleshoot some other problem and misunderstood what the setting does. The errors is bounded by the ranking. While 1/6th would be a fair significant error, even in very complex setups it's rarely anywhere close to that and you have so much going on in the pixel that it's really hard to notice. 

>  The assignment you wrote is indeed frowned upon due to it's very unstructured nature.

I'll leave that up to you. In my opinion, it's really important to be able to set up a Cryptomatte node in one action. My impression is doing it this way is the lesser of two evils. The setup is arcane, but there'd be no reason to mess with it, but I don't think you'd pass the whole channel setup down through your comp, I'd think it'd end at the cryptomatte node? My ignorance of Fusion is showing here however. Also, is it possible performance is better using channels rather than multiple input streams? 

> Again, thank you all, from both Kristof and I, for the trust and helpfulness, 

We're very happy to have you two on the project and grateful to have another implementation in the world. Thank you both very much for your continuing contributions.

**Pull request merged**
