### PR TITLE
major tool connection workflow upgrade

### PR DESCRIPTION
**Pull request by cedricduriau**
Changed workflow for fuse input, no longer requires the n amount of loaders to work. Populates loader channel slots with RGBA channels of rank pairs.

### CODE REVIEW

**Comment by cedricduriau** [comment]
I discovered an issue when having channels called crypto_material.R, the regex I wrote at first commit wasn't supporting non A-Z chars / non digits, so I replaced it by the .* to match any before hitting a dot separator for the actual channel name. The second commit is just a little cleanup, I still had a test image inside the process. Sorry about that.

I haven't implemented the numerical matte parsing yet, I will look into that for next commits / release.

Cheers
Cedric

**Comment by cedricduriau** [comment]
any updates on this request?

Cheers
Cedric

**Comment by acjones** [comment]
Hey Cedric,

Really sorry this took so long, and thanks for the nudge.  We did some testing today, and the new functionality definitely seems like the right way to go.  We did notice one thing, which is that the "Update Loader" button doesn't seem to work as expected.  If I view the Cryptomatte node, it updates the loader, and everything starts working.  But if I just push the button, the channels don't get reorganized.  I also noticed that the node doesn't seem to know how to update to a different set of Cryptomattes.  I.e., once it's been set to uCryptoObject, if I connect a loader with uCryptoMaterial, there doesn't seem to be a way to get those mattes to load.  The node stays stuck on uCryptoObject.  That might be something to look into.

Neither of these issues is a deal-breaker, and I'd actually rather get this version in the master branch right away, since it changes the user interaction significantly  So, we're happy to merge this now.  Do you want to call it "beta?"  We were thinking that might make sense, since there may be a known issue and it could probably use some additional testing out in the wild.

- Andy

**Comment by cedricduriau** [comment]
Hi Andy

No problem, just stoked about this specific commit :) The fact that pressing the button witout having the fuse in the view is related to the fact that the callback trigger is in the Process function, which only runs when active in the viewport. I'll see if I can write a standalone no view needed patch for that.

What you mention about the cryptomatte layer not updating, that I don't know of. I'll certainly look at that.

I'm fine with the beta release tag, I'll keep you posted on further dev.

Cheers
Cédric

**Pull request merged**
