### PR TITLE
CryptoCopy and CryptoRemove

### PR DESCRIPTION
**Pull request by dgirondi**
A Gizmo to copy Cryptomatte layers between pipes and another to remove them from pipes.

### CODE REVIEW

**Comment by jonahfriedman** [comment]
Hi Diogo- thanks for this. I don't think we can accept all of it yet. I think we should split it into two PRs- the input1s, and the new gizmos. It's best to have one issue per pull request. 

The parts we can accept right now are renaming input1s to "input". This is of course a 2-line change - but the key there is testing to make sure it doesn't break anything. To help test changes we have a test suite, if you aren't already familiar. These tests use all the Cryptomatte features, and then check that the results are as expected. You can run the tests from inside Nuke. We currently support Nuke 7+, and the test suite currently passes in all those versions. 

My suggestion for right now and the input1s change would be, first fork from the current head of the repo. From this clean state make the changes, test it, and create a pull request where you specify what you tested. This could include ability to open old Nuke scripts, what version of Nuke it was, and in which versions Nuke you ran the test suite.  We should consider adding tests for compatibility with old Nuke scripts as well. This would guard against breaking compatibility by accident. That test could do the equivalent of copy and pasting TCL - which [one test already does](https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities_tests.py#L145). 

For CryptoCopy and CryptoRemove, we should discuss the use cases for these. I'm not totally clear what they are right now, particularly for remove. Are these things you're currently using? First I'd like to fully understand what the use case for these is though. Afterward we can figure out how to develop them into fully supported parts of the system. 

Sorry if this seems like I'm being a stickler for process. It's all really about two things, avoiding breaking things by accident and maintenance burden. I'll leave this PR open for now to continue the discussion.

**Comment by dgirondi** [comment]
Hi Jonah,

Sorry for the mess, I’m a total newbie when it comes to Git. 

Renaming inputs should not break anything in Nuke as inputs are usually referenced by number and not their name. “Input1” node in a gizmo is usually input(0), so it shouldn't break anything unless you're explicitly referencing a input node by name. 

As for the gizmos the CryptoRemove is a WIP Gizmo to remove a specific Cryptomatte layer set and it's respective metadata from a pipe.

CryptoCopy is also a WIP Gizmo to copy a Cryptomatte layer and it's respective metadata from one pipe over to another. Useful to restore cryptomatte layers after doing operations where the metadata stream or layer access is broken'.

They both still require further work for sure. Currently they are storing a simplified dict from  the Cryptomatte metadata with the Cryptomatte key ID, name and channels (layers) names for when the node's layer selection is locked in order to be able to re-populate it.

Anyways, the CryptoCopy even though unfinished I've been using in production here in  nearly 100 shots so far without issues. 

The CryptoRemove however is something I did after discussing the option present on the Cryptomatte node to remove all layers except the RGBA one. Option that does not clean the metadata stream (since all the Cryptomatte meta remains present in the pipe) and might not be ideal since you may still need other layers like p, n, uv, z, etc preset after you're done with Cryptomatte in your tree.

Meanwhile I'll take some Git classes while I work on these to avoid creating chaos for you guys ;)


Cheers,
Diogo

**Comment by jonahfriedman** [comment]
No problem, gotta start somewhere. There is in fact [a place in the code where input1 is referenced explicity](https://github.com/Psyop/Cryptomatte/blob/master/nuke/cryptomatte_utilities.py#L226), so I expect the tests will probably fail with that change, but if so it's an easy fix. It is however a good demonstration of why we have the tests :)

For CryptoCopy, the use case makes sense.  What are the common operations which destroy metadata or layer access? 

To move forward on CryptoCopy, because it's a whole new gizmo, I think the first thing to do is have a bit of a wider discussion among other users about what sort of features we'd want for it. Things will very quickly become hard to change once it's out there. After that we should bring it into conformity with the way the other gizmos work where possible, and finally write some tests for it. (By the way, I'm not saying you have to do all this yourself, just giving you an idea of what the process would be). 

I think I'd hesitate to put in CryptoRemove if the only reason for it is to have a better version of the checkbox on the Cryptomatte gizmo, which I think doesn't have much of a use case anyway. Having the checkbox, a crappy feature that nobody is using, does not exactly justify making a more elaborate version. I'd actually prefer to go the other way, deprecate and hopefully remove it, maybe making it a hidden knob and a no-op rather than making a version of this feature with bells and whistles.

**Comment by dgirondi** [comment]
Removing channels is always useful, specially if there is no more use for them or they become something you don't want others using after a certain point in your tree. 

The problem with the built-in option on cryptomatte is that it will remove everything except the RGBA which isn't always desirable and will not clear the Cryptomatte metadata presence to any downstream node.

The second problem I see is that by performing that inside a single node things in your tree become harder to read and to debug case you find yourself asking why any given channel/layer isn't reaching a certain point in your tree. 

Using a Remove node that follows the appropriate color node scheme makes it really easy to find that point by just looking at the DAG. Not to mention that it will only remove the Cryptomatte layer you've selected and it's respective metadata leaving anything else intact. 

So in a situation where you have multiple Cryptomatte flowing in your pipe and at a certain point you have no use for one of them you can selectively remove just that layer set from your pipe.

As for maintaining these nodes personally I would adopt a version scheme instead of trying at all costs to keep everything on a single version. That way you can rest assured that when someone needs to restore a year old script from the archive it will still work.

But that is another discussion entirely. If you're interested we have a slack and git lab group to discuss standardizing Nuke "coding" workflows.

**Comment by jonahfriedman** [comment]
Happy New Year @dgirondi     . Sorry it took me a while to respond properly to this. I’m closing this now but we can continue the discussion here. 

> Removing channels is always useful, specially if there is no more use for them or they become something you don't want others using after a certain point in your tree.

> The problem with the built-in option on cryptomatte is that it will remove everything except the RGBA which isn't always desirable and will not clear the Cryptomatte metadata presence to any downstream node.

I agree. The option on the gizmo should either be removed, or fixed, and I’m leaning toward “fixed” though with mixed feelings. Removing it would entail hiding the knob and making it do nothing, which is a little gross as well. Fixing it does nothing about the issues you've talked about below. 

> The second problem I see is that by performing that inside a single node things in your tree become harder to read and to debug case you find yourself asking why any given channel/layer isn't reaching a certain point in your tree.

> Using a Remove node that follows the appropriate color node scheme makes it really easy to find that point by just looking at the DAG. Not to mention that it will only remove the Cryptomatte layer you've selected and it's respective metadata leaving anything else intact.

> So in a situation where you have multiple Cryptomatte flowing in your pipe and at a certain point you have no use for one of them you can selectively remove just that layer set from your pipe.

I also agree with this, I think readable node graphs are important for the same reason readable code is, and you wouldn’t want hidden side effects in a function either if you can avoid it. However, there is quite a lot that I’m weighing that against. Adding a gizmo in the main branch is something that will then need to be maintained, needs tests, needs docs, and the tests and docs themselves will also need to be maintained. We also need to be sure they cover the entire Cryptomatte standard, not just the whatever subset or use case they were made for. Once they’re in and released they become basically impossible to get rid of, even if they become unnecessary, because of our compatibility promises. 

So basically- to add a new gizmo, I need convincing that it’s A) necessary and B) the right form for this functionality to take. I think the best way for me to be convinced would be a discussion among other users on a forum such as the Nuke users list. There people can weigh in on whether they care, and what their uses cases are and whether this is the right way to address these issues. It’s also possible that this is all too much process and ceremony, and it’d be better to put them on Nukepedia, and if there’s a high rate of adoption, then look at merging. 

> As for maintaining these nodes personally I would adopt a version scheme instead of trying at all costs to keep everything on a single version. That way you can rest assured that when someone needs to restore a year old script from the archive it will still work.

Not to put too fine a point on it, but if it goes in this repo, it has to conform to everything else.  That means it works like everything else here, is versioned in the same way, has the same compatibility guarantees and has tests. That's not to say every pull request has to be perfect in every way of course, I'm more than welling to help fix things up, but the end result does need to be everything conforming.

**Comment by acjones** [comment]
Although I generally agree with what you guys have both said.  Removing Cryptomatte metadata as part of "Remove Channels" seems like a bugfix more than a feature change, so it's likely we should do that.

It's worth pointing out that the existing "Remove Channels" functionality does potentially serve a purpose for some people.  When creating a matte, as you would using a keyer, etc, it's not uncommon for a compositor to want to isolate the matte as a single mask channel or alpha.  For example, if a compositor wants to create a bunch of side-by-side Cryptomatte subgraphs to prepare a bunch of channel mattes, and recombine the mattes using a merge node, they would probably need to remove the other channels for this to work properly.  (There are lots of ways to merge/shuffle/copy channels, but the merge node has the advantage of supporting N inputs, meaning fewer additional nodes per additional matte.  The horizontal workflow here also helps avoid having to shift the upstream or downstream graphs).

This probably isn't a good enough argument to retroactively justify putting the Remove Channels feature in, but it may be a good enough argument for keeping it.  At the very least, I think it's something we need to investigate deeper before we remove/deprecate the option.

**Comment by dgirondi** [comment]
Happy new year guys!

I completely understand the reasoning to keep things simple and all into one single version. I've used to do that ages ago but I gave up on that idea after a few years. It quickly became inefficient and cumbersome for me to maintain and keep track of. Specially when it came to opening old archived scripts that were done with older versions of a specific gizmo.

So I've adopted a version scheme "gizmoname_v#.gizmo" and menus that automatically use the latest version of a gizmo available. That way old scripts can load the exact versions they've used at that time without me having to bother to make every new version mimic older version behaviors and be backwards compatible. That freed me up to completely change things internally or GUI wise at any point in time and just version up that gizmo. It's far from the cleanest approach but proved to be more sane and simpler for me to maintain.

Cryptomatte's gizmo "Remove Channels" option wise, I think that if it's there and in use there is no good reason to remove it or change it at this point. But leaving the metadata intact does seem like something that should be changed if feasible.

As for justifying the two nodes, CryptoCopy.gizmo was born on a project here where we were using V-Ray exclusively to generate the cryptomattes, everything else was being rendered via Maya Software due to the need of some crazy shaders that were unsupported by V-Ray. To avoid users not using Cryptomatte as intended I've created the node, that way artists could simply copy the crypto layers to a pipe and use Cryptomatte as intended.

Other good reasons that I can think of, are that sometimes some render artists here don't go the multi-layer EXR route even for projects that are coming from the same renderer and instead output one file sequence per element (stupid I know but it happens) and that was creating a mixed bag of terribly questionable approaches by Nuke artists here to make use of Cryptomatte. And another are those operations in Nuke that don't retain or affect all channels forcing you to restore (copy) things from different points of your tree.

CryptoRemove was created basically for the same reason, to standardize the removal or crypto layers (and just crypto layers) and its accompanying metadata in Nuke. Removing channels that serve no purpose is an important part of optimization and keeping scripts clean, so it felt like a natural thing to have. 

To sum it all up I'm of the opinion that if Cryptomatte is all about channels/layers it should come with a standard way to:

    1. **Make use of/Decode** its channels/layers/metadata (addressed by Cryptomatte)
    2. **Create/Encode** its channels/layers/metadata (addressed by Encryptomatte)
    3. **Copy** its channels/layers/metadata between pipes (currently missing)
    4. **Remove** its channels/layers/metadata from a pipe (currently missing)

For me 3 and 4 are currently missing, so I'll keep working on them on my fork along with other things   that I miss like a hierarchical list picker from the metadata in order to allow artists to pick mattes for objects/shaders that might not be visible at a given frame among other things. Once done, I might post them on Nukepedia and start from there.


Cheers!

**Pull request closed without merging**
