### PR TITLE
sidecar file fusion implementation

### PR DESCRIPTION
**Pull request by cedricduriau**
Hi guys

Just refactored and merged my branch sidecar_file into my master. This means that my master now holds an up to date version of both fusion and nuke sidecar_file implementations. All details are on the commit messages. In short, I implemented an error instead of trying to wing the rest of the code by faking empty dicts/tables when the manifest cannot be decoded.

Keep me posted!

Cheers
Cedric

### CODE REVIEW

**Comment by jonahfriedman** [comment]
Great, thank you. I'll merge this in and do a beta 3 very soon. 

For release notes:

- Added Fusion regex pattern matching
- Support for sidecar manifests
- Fixed updating issue when connecting fuse to different cryptomatte types
- Performance improvements

**Comment by jonahfriedman** [comment]
Also, how do you feel about removing the "beta" tags from the fusion implementation (after the 1.2 beta?)

**Comment by cedricduriau** [comment]
Hi Jonah

The regex pattern matching is not present in this branch. I will refactor my pattern branch upon this merge.
Fully agree on release notes and if removing the beta tag is fine for you, then it is for me.

I will keep you posted on the regex implementation, still battling with some Fusion behavior on the clamping side.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
Oh ok, I'll remove that from the notes. I thought I saw that in the commit message for d965ceb but it must be referring to something else.

**Comment by cedricduriau** [comment]
Oh hold on a second, you're right, when switching branches I must have comitted from the wrong one. Give me a second to rectify this.

**Comment by cedricduriau** [comment]
Hold on a second, you are right. When switching branches I must have comitted from the regex one. Give me a second to rectify this.

**Comment by jonahfriedman** [comment]
Ah, ok. 

If it's ready (enough) to go for a beta, feel free to leave it in, this is a beta release after all.

**Comment by cedricduriau** [comment]
Ah no sorry, I triple checked and I removed it in later commits, that is when I split my code into two branches. So sorry about that, green light it is!

PS: It is indeed ready for beta release, but I am a little picky on that side.

Cheers
Cedric

**Comment by jonahfriedman** [comment]
No problem. I've merged it locally into my dev branch, and this PR will automatically be closed when the master branch becomes that. Thanks!

**Comment by cedricduriau** [comment]
Alright. Always a pleasure and thank you!

Cheers
Cedric

**Pull request merged**
